name: my_card
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
   - imagens/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Light.ttf
        
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
       
    - family: Patrick Hand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
 

 